### ISSUE TITLE
down load error : subprocess - exited - with - error during down loading "파이썬으로 즐기는 횡스크롤 게임"

### ISSUE THREAD

**Issue by piescestw** [needleworm/python101#1]
<html>
<body>
<div class="nH aHU" style="position: relative; color: rgb(32, 33, 36); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="nH hx" style="background-color: transparent; color: rgb(34, 34, 34); min-width: 502px; padding: 0px;"><div class="nH" jslog="20686; u014N:xr6bB" role="list"><div class="h7 ie nH oy8Mbf" role="listitem" aria-expanded="true" tabindex="-1" style="clear: both; padding-bottom: 0px; max-width: 100000px; outline: none;"><div class="Bk" style="position: relative; margin-bottom: 0px; border-width: 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(239, 239, 239); border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-color: initial; border-radius: 0px; float: left; width: 1789.81px;"><div class="G3 G2" style="padding-top: 0px; background-color: transparent; border-right: 0px; border-bottom: 0px rgba(100, 121, 143, 0.12); border-left: 0px; border-image: initial; border-top: none; border-radius: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px;"><div><div id=":12h"><div class="adn ads" data-message-id="#msg-a:r-2352242902250015812" data-legacy-message-id="18566332d81382fe" style="border-left: none; padding: 0px; display: flex;"><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1717.83px;"><div class=""><div id=":12k" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":12j" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="ltr">안녕하세요 강사님 저는 회사원 김태우 라고 합니다.<div><br><div>강의 진행 중 질의 사항 있을 시 메일 드려도 될까 하여 문의 드립니다.<br><div>파이썬 기초 강의를 듣고 있는데 말씀 하신 대로 실행 하는 과정에서 에러가 나는데 어떻게 똑같이 진행 했는데 에러가 나고 이럴때 어떻게 해야 하는지 문의는 어디로 드리면 될까요? 해당 에러는 "파이썬으로 즐기는 횡스크롤 게임" 실행 과정에서 역시 terminal 을 통하여 진행이 되지 않아 python console 을 실행 하여 복 붙하고 다운 로드중 에러가 발생 하여 문의 드립 니다 자세한 에러 내용은 아래 스크립트 참고 해주시면 감사하겠습니다.<br>ARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.<br>Please see<span> </span><a href="https://github.com/pypa/pip/issues/5599" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://github.com/pypa/pip/issues/5599&amp;source=gmail&amp;ust=1672543320218000&amp;usg=AOvVaw355lEg8ewzYY_gtsvl8eQf" style="color: rgb(17, 85, 204);">https://github.com/pypa/pip/<wbr>issues/5599</a><span> </span>for advice on fixing the underlying issue.<br>To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.<br>Collecting pygame<br>  Using cached pygame-2.1.2.tar.gz (10.1 MB)<br>  Preparing metadata (setup.py): started<br>  Preparing metadata (setup.py): finished with status 'error'<br>  error: subprocess-exited-with-error<br> <br>  × python setup.py egg_info did not run successfully.<br>  │ exit code: 1<br>  ╰─&gt; [77 lines of output]<br>     <br>     <br>      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"<br>      Using WINDOWS configuration...<br>     <br>      Making dir :prebuilt_downloads:<br>      Downloading...<span> </span><a href="https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip&amp;source=gmail&amp;ust=1672543320218000&amp;usg=AOvVaw2NIs9FCB0CSLdmvKE54DHv" style="color: rgb(17, 85, 204);">https://www.libsdl.org/<wbr>release/SDL2-devel-2.0.18-VC.<wbr>zip</a><span> </span>ed561079ec622b0bab5a9e02976f5d<wbr>540b0622da<br>      Unzipping :prebuilt_downloads\SDL2-<wbr>devel-2.0.18-VC.zip:<br>      Downloading...<span> </span><a href="https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip&amp;source=gmail&amp;ust=1672543320218000&amp;usg=AOvVaw2MVXyE9gU42AcQ4VgV5A9M" style="color: rgb(17, 85, 204);">https://www.libsdl.org/<wbr>projects/SDL_image/release/<wbr>SDL2_image-devel-2.0.5-VC.zip</a><span> </span>137f86474691f4e12e76e07d58d592<wbr>0c8d844d5b<br>      Unzipping :prebuilt_downloads\SDL2_<wbr>image-devel-2.0.5-VC.zip:<br>      Downloading...<span> </span><a href="https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip&amp;source=gmail&amp;ust=1672543320218000&amp;usg=AOvVaw1vaQGIGbsyfk8Isa5kfWxc" style="color: rgb(17, 85, 204);">https://www.libsdl.org/<wbr>projects/SDL_ttf/release/SDL2_<wbr>ttf-devel-2.0.15-VC.zip</a><span> </span>1436df41ebc47ac36e02ec9bda5699<wbr>e80ff9bd27<br>      Unzipping :prebuilt_downloads\SDL2_ttf-<wbr>devel-2.0.15-VC.zip:<br>      Downloading...<span> </span><a href="https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip&amp;source=gmail&amp;ust=1672543320219000&amp;usg=AOvVaw3l4A-s6EDKyJ7ZXX6wz_f4" style="color: rgb(17, 85, 204);">https://www.libsdl.org/<wbr>projects/SDL_mixer/release/<wbr>SDL2_mixer-devel-2.0.4-VC.zip</a><span> </span>9097148f4529cf19f805ccd007618d<wbr>ec280f0ecc<br>      Unzipping :prebuilt_downloads\SDL2_<wbr>mixer-devel-2.0.4-VC.zip:<br>      Downloading...<span> </span><a href="https://www.pygame.org/ftp/jpegsr9d.zip" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.pygame.org/ftp/jpegsr9d.zip&amp;source=gmail&amp;ust=1672543320219000&amp;usg=AOvVaw2UrquWm2t7VFFHtFrfSty7" style="color: rgb(17, 85, 204);">https://www.pygame.org/ftp/<wbr>jpegsr9d.zip</a><span> </span>ed10aa2b5a0fcfe74f8a6f7611aeb3<wbr>46b06a1f99<br>      Unzipping :prebuilt_downloads\jpegsr9d.<wbr>zip:<br>      Downloading...<span> </span><a href="https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip&amp;source=gmail&amp;ust=1672543320219000&amp;usg=AOvVaw1irrNPWuqvOlmbIbpL1zqP" style="color: rgb(17, 85, 204);">https://pygame.org/ftp/<wbr>prebuilt-x64-pygame-1.9.2-<wbr>20150922.zip</a><span> </span>3a5af3427b3aa13a0aaf5c4cb08daa<wbr>ed341613ed<br>      Unzipping :prebuilt_downloads\prebuilt-<wbr>x64-pygame-1.9.2-20150922.zip:<br>      copying into .\prebuilt-x64<br>      Path for SDL: prebuilt-x64\SDL2-2.0.18<br>      ...Library directory for SDL: prebuilt-x64/SDL2-2.0.18/lib/<wbr>x64<br>      ...Include directory for SDL: prebuilt-x64/SDL2-2.0.18/<wbr>include<br>      Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15<br>      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/<wbr>lib/x64<br>      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/<wbr>include<br>      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5<br>      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/<wbr>lib/x64<br>      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/<wbr>include<br>      Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4<br>      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/<wbr>lib/x64<br>      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/<wbr>include<br>      Path for PORTMIDI: prebuilt-x64<br>      ...Library directory for PORTMIDI: prebuilt-x64/lib<br>      ...Include directory for PORTMIDI: prebuilt-x64/include<br>      DLL for SDL2: prebuilt-x64/SDL2-2.0.18/lib/<wbr>x64/SDL2.dll<br>      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/<wbr>lib/x64/SDL2_ttf.dll<br>      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/<wbr>lib/x64/SDL2_image.dll<br>      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/<wbr>lib/x64/SDL2_mixer.dll<br>      DLL for portmidi: prebuilt-x64/lib/portmidi.dll<br>      Path for FREETYPE not found.<br>      ...Found include dir but no library dir in prebuilt-x64.<br>      Path for PNG not found.<br>      ...Found include dir but no library dir in prebuilt-x64.<br>      Path for JPEG not found.<br>      ...Found include dir but no library dir in prebuilt-x64.<br>      DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/<wbr>lib/x64/libfreetype-6.dll<br>     <br>      ---<br>      For help with compilation see:<br>         <span> </span><a href="https://www.pygame.org/wiki/CompileWindows" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.pygame.org/wiki/CompileWindows&amp;source=gmail&amp;ust=1672543320219000&amp;usg=AOvVaw1Jig_cnWyhN6liHtjxUz1G" style="color: rgb(17, 85, 204);">https://www.pygame.org/wiki/<wbr>CompileWindows</a><br>      To contribute to pygame development see:<br>         <span> </span><a href="https://www.pygame.org/contribute.html" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.pygame.org/contribute.html&amp;source=gmail&amp;ust=1672543320219000&amp;usg=AOvVaw0wioyfuIQpx3Qp5KkZ-vpV" style="color: rgb(17, 85, 204);">https://www.pygame.org/<wbr>contribute.html</a><br>      ---<br>     <br>      Traceback (most recent call last):<br>        File "&lt;string&gt;", line 2, in &lt;module&gt;<br>        File "&lt;pip-setuptools-caller&gt;", line 34, in &lt;module&gt;<br>        File "C:\Users\USER\AppData\Local\<wbr>Temp\pip-install-3na5zptl\<wbr>pygame_<wbr>cce51d5ce84f40189a38ab194aa910<wbr>33\setup.py", line 359, in &lt;module&gt;<br>          buildconfig.config.main(AUTO_<wbr>CONFIG)<br>        File "C:\Users\USER\AppData\Local\<wbr>Temp\pip-install-3na5zptl\<wbr>pygame_<wbr>cce51d5ce84f40189a38ab194aa910<wbr>33\buildconfig\config.py", line 225, in main<br>          deps = CFG.main(**kwds)<br>                 ^^^^^^^^^^^^^^^^<br>        File "C:\Users\USER\AppData\Local\<wbr>Temp\pip-install-3na5zptl\<wbr>pygame_<wbr>cce51d5ce84f40189a38ab194aa910<wbr>33\buildconfig\config_win.py", line 511, in main<br>          return setup_prebuilt_sdl2(prebuilt_<wbr>dir)<br>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^<br>        File "C:\Users\USER\AppData\Local\<wbr>Temp\pip-install-3na5zptl\<wbr>pygame_<wbr>cce51d5ce84f40189a38ab194aa910<wbr>33\buildconfig\config_win.py", line 471, in setup_prebuilt_sdl2<br>          DEPS.configure()<br>        File "C:\Users\USER\AppData\Local\<wbr>Temp\pip-install-3na5zptl\<wbr>pygame_<wbr>cce51d5ce84f40189a38ab194aa910<wbr>33\buildconfig\config_win.py", line 336, in configure<br>          from . import vstools<br>        File "C:\Users\USER\AppData\Local\<wbr>Temp\pip-install-3na5zptl\<wbr>pygame_<wbr>cce51d5ce84f40189a38ab194aa910<wbr>33\buildconfig\vstools.py", line 11, in &lt;module&gt;<br>          compiler.initialize()<br>        File "C:\Users\USER\AppData\Local\<wbr>Programs\Python\Python311\Lib\<wbr>site-packages\setuptools\_<wbr>distutils\msvc9compiler.py", line 403, in initialize<br>          vc_env = query_vcvarsall(VERSION, plat_spec)<br>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^<br>        File "C:\Users\USER\AppData\Local\<wbr>Programs\Python\Python311\Lib\<wbr>site-packages\setuptools\_<wbr>distutils\msvc9compiler.py", line 281, in query_vcvarsall<br>          raise DistutilsPlatformError("Unable to find vcvarsall.bat")<br>      distutils.errors.<wbr>DistutilsPlatformError: Unable to find vcvarsall.bat<br>      [end of output]<br> <br>  note: This error originates from a subprocess, and is likely not a problem with pip.<br>error: metadata-generation-failed<br>× Encountered error while generating package metadata.<br>╰─&gt; See above for output.<br>note: This is an issue with the package mentioned above, not pip.<br>hint: See above for details.<br>Traceback (most recent call last):<br>  File "&lt;input&gt;", line 17, in &lt;module&gt;<br>  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\<wbr>helpers\pydev\_pydev_bundle\<wbr>pydev_import_hook.py", line 21, in do_import<br>    module = self._system_import(name, *args, **kwargs)<br>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^<br>ModuleNotFoundError: No module named 'pygame'<br>During handling of the above exception, another exception occurred:<br>Traceback (most recent call last):<br>  File "&lt;input&gt;", line 23, in &lt;module&gt;<br>  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\<wbr>helpers\pydev\_pydev_bundle\<wbr>pydev_import_hook.py", line 21, in do_import<br>    module = self._system_import(name, *args, **kwargs)<br>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^<br>ModuleNotFoundError: No module named 'pygame'<br>During handling of the above exception, another exception occurred:<br>Traceback (most recent call last):<br>  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\<wbr>helpers\pydev\pydevconsole.py"<wbr>, line 364, in runcode<br>    coro = func()<br>           ^^^^^^<br>  File "&lt;input&gt;", line 26, in &lt;module&gt;<br>  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\<wbr>helpers\pydev\_pydev_bundle\<wbr>pydev_import_hook.py", line 21, in do_import<br>    module = self._system_import(name, *args, **kwargs)<br>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^<wbr>^^^^^^^^^^^^^<br>ModuleNotFoundError: No module named 'pygame'<br></div></div></div><div><br></div><div>감사합니다. 김태우 드림</div><div class="yj6qo"></div><div class="adL"><br></div></div><div class="adL"></div></div></div><div class="hi" style="border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; padding: 0px; width: auto; background: rgb(242, 242, 242); margin: 0px;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: transparent;"><div class="gB xu" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":12l">

  | 답장전달
-- | --

</div></div></div></div></div></div></div></div></div></div><div class="nH"></div><div class="nH"></div></div></div><div class="nH" style="color: rgb(32, 33, 36); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
</body>
</html>

**Comment by needleworm** [comment]
업데이트 되었습니다. 다시 풀 받아서 시도해 보시기 바랍니다.
